version: "3.9"

services:
  math-api:
    build: .
    container_name: math-api
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./requests.db:/app/requests.db

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mathdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql

volumes:
  dbdata:
