version: "3.9"

services:
  math-api:
    build: .
    container_name: math-api
    ports:
      - "5000:5000"
    volumes:
      - ./app:/app
      - ./requests.db:/app/requests.db
    depends_on:
      - kafka
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: mathdb
      MYSQL_USER: user
      MYSQL_PASSWORD: userpass
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_LISTENERS: PLAINTEXT://0.0.0.0:9092
      KAFKA_LOG4J_LOGGERS: "kafka.controller=WARN,kafka.producer.async=WARN,state.change.logger=ERROR"
      KAFKA_LOG4J_ROOT_LOGLEVEL: WARN
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
volumes:
  dbdata:
